---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
data:
  index.html: |
    <html>
    <h2>Hello world 1!!</h2>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testService: service1
    spec:
      containers:
      - name: nginx
        image: registry.ocp.local:8443/init/mirror/nginxinc/nginx-unprivileged:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-config
        configMap:
          name: nginx-config-1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    testService: service-1
  ports:
  - name: http
    port: 80
    targetPort: 80